<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\AiApplication.Application\AiApplication.Application.csproj" />
    <ProjectReference Include="..\AiApplication.Infrastructure\AiApplication.Infrastructure.csproj" />
  </ItemGroup>

</Project>
